# Generated by Django 5.0.8 on 2024-11-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albanjari", "0003_category_category_image_userprofile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_image",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products_images/"
            ),
        ),
    ]
